### ISSUE TITLE
Faux groups not collapsing

### ISSUE THREAD

**Issue by EelmanE** [skttl/umbraco-matryoshka#43] opened 2020-10-30 11:26 UTC
The tabs are working as expected but the faux groups are not. When i put a group separator between my properties it only collapses and expends itselve and not the properties underneath. Am i missing something? I've tried it on umbraco v8.8 and today upgraded to v8.9 but the issue remains.

![tabs](https://user-images.githubusercontent.com/73697646/97699756-fad5a500-1aaa-11eb-8ac7-933453113a13.gif)

**Comment by skttl** [comment] 2020-11-01 17:53
Duplicate of #32 fixed in #33

**Closed by skttl** 2020-11-01 17:53 UTC
