### ISSUE TITLE
Layout broken when using nested Doc Type Grid Editor and Matryoshka

### ISSUE THREAD

**Issue by giordanop** [skttl/umbraco-matryoshka#46] opened 2020-12-10 13:53 UTC
Hi, when I use nested Doc Type Grid Editor and Matryoshka, the layout in the Content editor is broken (see image):
![image](https://user-images.githubusercontent.com/11761097/101779711-ec40cb80-3af5-11eb-8df2-be47a7e4e1d7.png)

**Description:**
I'm on Umbraco CMS 8.9.0, DTGE 1.2.6 and Matryoshka 0.7.0.

I'm implementing an accordion component and I want to use it in the grid editor. this is the structure:

Accordion Container
-Accordion Section 1 
--Accordion Item 1.1
--Accordion Item 1.2
--Accordion Item 1.3
-Accordion Section 2
--Accordion Item 2.1
--Accordion Item 2.2
--Accordion Item 2.3
..etc..

Sections and Items are configured as Nested Content (see image)

![image](https://user-images.githubusercontent.com/11761097/101779365-79375500-3af5-11eb-82cb-d8cd7220c66a.png)
![image](https://user-images.githubusercontent.com/11761097/101779398-85bbad80-3af5-11eb-8233-6c0253c3d7bf.png)

**Issue:**
When I create or edit the accordion content, I go to Content, then to the page where I want to add the component, then I add the component to the grid, then I would fill the content of the accordion sections and items, but the layout is broken, as you can see on the image on top. 

**Solutions?**
- If I uninstall Matryoshka, the layout is fixed, but then I loose the tab improvement in the whole CMS (see image)
![image](https://user-images.githubusercontent.com/11761097/101780389-c9fb7d80-3af6-11eb-8922-24d9cb735e93.png)

- Is there a way to disable Matryoshka for nested content? Or can you fix this issue or I'm making anything wrong?

Thanks,
Giordano

**Comment by skttl** [comment] 2020-12-10 14:32
As a workaround, you can set the editor to large, then you should have some more space to show the editors.

**Comment by giordanop** [comment] 2020-12-10 14:43
Hi @skttl , thanks for your quick reply. Do you mean adding  custom css rule (like here: https://our.umbraco.com/packages/backoffice-extensions/stacked-content/stacked-content-feedback/91293-change-width-of-editor-pane-overlay#comment-288080)? 
Or is there a better way to do it?

Thanks!
Giordano

**Comment by skttl** [comment] 2020-12-10 14:52
No, set the overlaySize to large in your Doc Type Grid Editor :)
https://github.com/skttl/umbraco-doc-type-grid-editor/blob/develop/docs/developers-guide.md#configuring-the-doc-type-grid-editor

**Comment by giordanop** [comment] 2020-12-10 15:39
Oh nice thanks! I fixed using "large" 👍 
I find reasonable that, for showing such amount of controls, the panel needs more space. 
Since there is an elegant way to increase the width, this issue doesn't sound to me as a bug anymore.
Therefore, it's up to you to close it or to make some improvements anyway. 

Thanks,
Giordano

**Comment by skttl** [comment] 2020-12-10 19:51
I think for small overlays, the labels should be on top of the editors at least :)

**Comment by skttl** [comment] 2021-02-05 19:52
Dupe of #41 fixed in b17d97c99389aa9c4afdcc674a35640310243345

**Closed by skttl** 2021-02-05 19:52 UTC
