### ISSUE TITLE
Group Separator Expand / Collapse functionality is broken in 8.7

### ISSUE THREAD

**Issue by mjbarlow** [skttl/umbraco-matryoshka#32] opened 2020-09-16 11:05 UTC
In v8.7 the expand and collapse functionality doesn't work for the group separator. 

I installed a clean version of 8.7 with the latest matryoshka and added a group separator, as you can see the property editors aren't captured inside of the expand / collapse functionality.

![matryoshka_error](https://user-images.githubusercontent.com/1984515/93329103-fa47be80-f81c-11ea-9bd1-cf777209827d.gif)

**Comment by chris-evansnz** [comment] 2020-09-27 21:24
I'm also encountering this issue, umbraco version 8.7 and Our.Umbraco.Matryoshka version 0.5.0

There isn't much documentation around how the Matryoshka Group Separator is supposed to be used or configured, but I assume you're just meant to add one in front of the properties you want to include in the group?

**Comment by FransdeJong** [comment] 2020-10-08 13:14
I fixed this in https://github.com/skttl/umbraco-matryoshka/pull/33

The issue is that since 8.7 Umbraco introduced a umb-property directive.
This wraps the div with the class umb-property where the matryoshka classes were added to.

To maintain backwards compatibility I check if the div with class umbr-directive has a parent element umb-directive. If so I assign it to separator so all logic on the our-matryoshka-group-separator-container class works as intended.

Also I had to do some small css changes to fix the way the separators are displayed.

**Closed** 2020-10-12 19:22 UTC
